### ISSUE TITLE
Preparation

### ISSUE THREAD

**Issue by jmuheim** [Access4all/developer-guide#7]
Dieser ganze Bereich wurde zur einer Zeit erstellt, als der ADG noch blosses Screenreader-Tutorial sein sollte. U.U. muss man den gesamten Bereich in Frage stellen bzw. woandershin verfrachten? Es gäbe die Möglichkeit, hier Installationsanleitungen für unterschiedlichste Tools anzubieten (Firebug, WAT, WAVE...), so dass diese auch aus den Recipes heraus referenziert werden könnten. Der Bereich könnte dann "Tools" genannt werden.
- [Overview](http://developer-guide.access4all.ch/en/pages/preparation_overview)
- [Screenreader installation](http://developer-guide.access4all.ch/en/pages/screenreader_installation)
- [I don't use Windows!](http://developer-guide.access4all.ch/en/pages/i_dont_use_windows)
- [Keyboard navigation basics](http://developer-guide.access4all.ch/en/pages/keyboard_navigation_basics)

**Comment by AntonBolfing** [comment]
Besten Dank für Ihre Nachricht.

Ich bin bis am Dienstag, dem 9. Mai 2017 abwesend und kann Ihre Nachricht erst ab dann wieder bearbeiten. Ihre Email wird nicht weitergeleitet.
In dringenden Fällen wenden Sie sich bitte an Herrn Bernhard Heinser: bernhard.heinser@access-for-all.ch

Beste Grüsse

Anton Bolfing

*******************************************************

Thank you for your message.

I'm out of office until Tuesday, May 9, 2017.  I will not respond to your email until then.

Best regards

Anton Bolfing
